apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: metrics
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
  name: logging-logan-fluentd
  namespace: logging
spec:
  ClusterIP: None
  ports:
  - name: proxy
    port: 24231
  selector:
    component: fluentd
    provider: openshift